-- Create a new table for email subscribers
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    active BOOLEAN DEFAULT TRUE
);

-- Enable Row Level Security
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to insert (subscribe)
CREATE POLICY "Anyone can subscribe" ON subscribers
    FOR INSERT
    TO public
    WITH CHECK (true);

-- Create policy to allow only authenticated users to view subscribers
CREATE POLICY "Only authenticated users can view subscribers" ON subscribers
    FOR SELECT
    TO authenticated
    USING (true); 