-- Drop existing table if it exists (this ensures we start fresh)
DROP TABLE IF EXISTS public.favorites;

-- Create favorites table
CREATE TABLE public.favorites (
    id bigint generated by default as identity primary key,
    book text,
    music text,
    tv text,
    updated_at timestamptz default now()
);

-- Insert initial row
INSERT INTO public.favorites (book, music, tv)
VALUES (
    'Southernmost - Silas House',
    'Women and Children First - Van Halen',
    'Fleabag - Phoebe Waller-Bridge'
); 